# see https://docs.github.com/ja/repositories/releasing-projects-on-github/automatically-generated-release-notes
changelog:
  categories:
    - title: 'Update langs'
      labels:
        - 'docker'
    - title: 'Update gems'
      labels:
        - 'ruby'
    - title: 'Bug Fixes'
      labels:
        - 'fix'
        - 'bug'
  exclude:
    labels:
      - 'skip-changelog'
      - 'github_actions'
