# see https://github.com/release-drafter/release-drafter#configuration
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Update langs'
    label: 'docker'
  - title: 'Update gems'
    label: 'ruby'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
exclude-labels:
  - 'skip-changelog'
  - 'github_actions'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor
template: |
  ## Changes

  $CHANGES
