name: 'Pronto Action'
description: 'Github action of Pronto'
author: 'HeRoMo'
branding:
  icon: 'code'
  color: 'blue'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: false
    default: ${{ github.token }}
  commit:
    description: 'Commit for the diff.'
    required: false
    default: 'origin/master'
  runner:
    description: 'Run only the passed runners.'
    required: false
    default: 'rubocop'
  formatters:
    description: 'Pick output formatters.'
    required: false
    default: 'github_status github_pr'
  path:
    description: 'Relative path to check'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: docker://ghcr.io/heromo/pronto-action:1.6.0
  entrypoint: '/pronto/entrypoint.sh'
