version: '3'
services:
  pronto:
    image: hero/pronto-action:0.4.0
    volumes:
      - .:/pronto
    command: pronto run -r rubocop
volumes:
  bundle_install:
    driver: local
  bundle:
    driver: local
