services:
  pronto:
    build:
      context: .
      dockerfile: Dockerfile
    image: pronto-action.dev
    volumes:
      - .:/pronto
      - bundle_install:/usr/local/bundle
      - bundle:/app/.bundle
volumes:
  bundle_install:
    driver: local
  bundle:
    driver: local
