version: '3'
services:
  pronto:
    image: ghcr.io/heromo/pronto-action:1.43.1
    volumes:
      - .:/app
    entrypoint: ["bundle", "exec", "pronto"]
    command: run /app -r rubocop

# Run the following command to run pronto locally
# > docker-compose -f docker-compose-pronto.yml run --rm pronto
# > docker-compose -f docker-compose-pronto.yml run --rm pronto run /app -r rubocop --staged
