name: Build and Test
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - Dockerfile
      - Gemfile
      - Gemfile.lock
      - entrypoint.sh
      - test/**
      - .github/workflows/ci.yml
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: heromo/pronto-action

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 60
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          load: true
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      - name: Modify action.yaml
        run: yq '.runs.image = "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"' -i action.yaml
      - name: Prepare Tests
        run: |
          cp -rf ./test ./test-tmp
          git config --global user.email "test@example.com"
          git config --global user.name "Tester"
          git add -f ./test-tmp
          git commit -m 'for test'
      - name: Test Local Action
        uses: ./
        with:
          runner: rubocop
          path: ./test-tmp/
          formatters: text
