name: Pronto
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  pronto:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: HeRoMo/pronto-action@1.45.0
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
