name: Pronto
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  pronto:
    runs-on: ubuntu-latest
    if: ${{$(jq -r '[.pull_request.labels[].name]|contains(["enhancement"])' $GITHUB_EVENT_PATH)}}
    steps:
      - uses: actions/checkout@v1
      - uses: HeRoMo/pronto-action@v0.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: $(jq '[.pull_request.labels[].name]|contains(["enhancement"])' $GITHUB_EVENT_PATH)
